# Generated by Django 5.2 on 2025-04-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_contactado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contactado',
            new_name='contactado',
        ),
    ]
