# Generated by Django 5.2 on 2025-04-08 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del curso')),
                ('content', models.TextField(verbose_name='Contenido del curso')),
                ('Enlace_Oficial', models.URLField(verbose_name='Enlace oficial a Django')),
                ('Created_At', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
        ),
    ]
