# Generated by Django 5.2 on 2025-04-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='toc',
            field=models.FileField(blank=True, null=True, upload_to='courses/toc/', verbose_name='Temario'),
        ),
    ]
