# Generated by Django 5.2 on 2025-04-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='courses/images/', verbose_name='Portada del curso'),
        ),
    ]
